stages:

  build_vector_store:
    cmd: python Pipeline/embeddings_2/build_vector_store.py
    deps:
      - Pipeline/embeddings_2/build_vector_store.py
      - Pipeline/data_1/Mukku_Sumanth_Updated_Resume_IT.pdf
    outs:
      - Pipeline/embeddings_2/vector_store/

  query_test:
    cmd: python Pipeline/embeddings_2/query_vector_store.py
    deps:
      - Pipeline/embeddings_2/query_vector_store.py
      - Pipeline/embeddings_2/vector_store/

  run_rag_api:
    cmd: uvicorn Pipeline.api_6.main:app --reload
    deps:
      - Pipeline/api_6/main.py
      - Pipeline/embeddings_2/query_vector_store.py
      - Pipeline/agent_5/hybrid_agent.py
